### ISSUE TITLE
cant run the samples

### ISSUE THREAD

**Issue by LeiTi** [Microsoft/SparkCLR#35]
Error: Could not find or load main class org.apache.spark.launcher.SparkCLRSubmitArguments

em... can someone tell me why?

**Comment by skaarthik** [comment]
Can you share the steps you are following to run the samples? There are multiple deployment modes and we would like to make sure that the steps you are following are supported/tested.

**Comment by LeiTi** [comment]
i follow the step from https://ci.appveyor.com/project/skaarthik/SparkCLR/branch/master and set the environment variables.

 Then uncommit the setting
`<add key="CSharpWorkerPath" value="C:\SparkCLR-master\SparkCLR-master\csharp\Samples\Microsoft.Spark.CSharp\bin\Release\CSharpWorker.exe"/> `
and run command 
`sparkclr-submit.cmd --verbose -exe SparkCLRSamples.exe  %SPARKCLR_HOME%\samples spark.local.dir C:\temp\SparkCLRTemp sparkclr.sampledata.loc %SPARKCLR_HOME%\data`

**Comment by LeiTi** [comment]
em..anyway i change the sparkclr-submit.cmd

`"%JAVA_HOME%\bin\java" -cp %LAUNCH_CLASSPATH% org.apache.spark.launcher.SparkCLRSubmitArguments %* > %LAUNCHER_OUTPUT%`

simply because my %JAVA_HOME% include space and it go wrong here.

**Comment by tawan0109** [comment]
Please try below cmd again with latest code, we just merged some changes.

 sparkclr-submit.cmd --verbose --exe SparkCLRSamples.exe %SPARKCLR_HOME%\samples spark.local.dir C:\temp\SparkCLRTemp sparkclr.sampledata.loc %SPARKCLR_HOME%\data sparkclr.samples.torun PiSample

**Comment by LeiTi** [comment]
i use the latest code and it still can't run. 
`Could not find or load main class org.apache.spark.launcher.SparkCLRSubmitArguments`

can someone tell me is there exist a main class in `spark-clr-1.4.1-SNAPSHOT.jar\org\apache\spark\launcher` if it compile successful?

**Comment by skaarthik** [comment]
@tawan0109 - please follow-up with @LeiTi. Once the issue is resolved @LeiTi  can close the issue.

**Comment by tawan0109** [comment]
Hi LeiTi, please check whether %SPARKCLR_HOME% is set properly, and spark-clr-1.4.1-SNAPSHOT.jar can be found under %SPARKCLR_HOME%\lib. If still can't work, please make below modifications to your scripts/sparkclr-submit.cmd, rerun it and send us the output, we will use it for diagnosis.

(line 41)
```
-%JAVA_HOME%\bin\java -cp %LAUNCH_CLASSPATH% org.apache.spark.launcher.SparkCLRSubmitArguments %* > %LAUNCHER_OUTPUT%
+echo %JAVA_HOME%\bin\java -cp %LAUNCH_CLASSPATH% org.apache.spark.launcher.SparkCLRSubmitArguments %* 
+goto :eof
```

**Comment by LeiTi** [comment]
`C:\Program Files\Java\jdk1.8.0_65\bin\java -cp ;D:\sparkCLRHome\lib\spark-clr-1.4.1-SNAPSHOT.jar;D:\sparkcsv\commons-csv-1.2.jar;D:\sparkcsv\spark-csv_2.11-1.2.0.jar org.apache.spark.launcher.SparkCLRSubmitArguments --verbose --exe SparkCLRSamples.exe D:\sparkCLRHome\samples spark.local.dir C:\temp\SparkCLRTemp sparkclr.sampledata.loc D:\sparkCLRHome\data`

**Comment by tawan0109** [comment]
It looks like spark-assembly-1.4.1-hadoop2.6.0.jar is missing in the classpath. Would you please check whether %SPARK_HOME% has been set properly, and spark-assembly-1.4.1-hadoop2.6.0.jar can be found under %SPARK_HOME%\lib?

**Comment by LeiTi** [comment]
ya. i found that there is no folder name lib under SPARK_HOME...and  `spark-assembly-1.4.1-hadoop2.4.0.jar` is under folder assembly...

**Comment by danielli90** [comment]
It seems you didn't download spark bits, before running the samples.

Sent from my Windows Phone
________________________________

**Comment by LeiTi** [comment]
u r right. i build it use mvn by myself. now i download spark-bin and it run.
i think we can close this issue. thk all.

**Comment by sehunley** [comment]
I am currently trying to run the samples for SparkCLR and the local samples from within the localmode folder works great.  However, when trying to execute the samples against my Spark server (cluster) using the sparkclr-submit.cmd script:

>C:\MyData\Apache_Spark\SparkCLR-master\build\runtime>sparkclr-submit.cmd --verbose --master spark://spark01:7077 --exe SparkCLRSamples.exe  %SPARKCLR_HOME%\samples spark.local.dir %SPARKCLR_HOME%\Temp sparkclr.sampledata.loc %SPARKCLR_HOME%\data

 I am getting the following error:
The system cannot find the path specified.
SPARKCLR_JAR=spark-clr_2.10-1.6.0-SNAPSHOT.jar
Error: Could not find or load main class org.apache.spark.launcher.SparkCLRSubmitArguments

is this another environment variable that needs to be set?  I have the SPARKCLR_HOME and  JAVA_HOME variables.  Are there more that are needed?

Thanks all.
